import type { GameMeta } from "@shared/types/room";

export const GAME_REGISTRY: GameMeta[] = [
  {
    id: "reaction-buzzer",
    title: "Reaction Buzzer",
    description: "Tap the matching button fastest to score.",
    minPlayers: 1,
    maxPlayers: 8,
    requiresMotion: false,
    requiresPointer: false,
  },
  {
    id: "tilt-maze",
    title: "Tilt Maze",
    description: "Tilt your phone to roll your ball through the maze.",
    minPlayers: 1,
    maxPlayers: 4,
    requiresMotion: true,
    requiresPointer: false,
  },
  {
    id: "laser-blaster",
    title: "Laser Blaster",
    description: "Point your phone like a laser and tap to fire at targets.",
    minPlayers: 1,
    maxPlayers: 4,
    requiresMotion: true,
    requiresPointer: true,
  },
  {
    id: "fruit-slice",
    title: "Fruit Slice",
    description: "Point your phone at the fruit to slice it. Avoid bombs.",
    minPlayers: 1,
    maxPlayers: 4,
    requiresMotion: true,
    requiresPointer: true,
  },
  {
    id: "simon-says",
    title: "Simon Says",
    description: "Watch the pattern, then repeat it back before it's too late.",
    minPlayers: 1,
    maxPlayers: 8,
    requiresMotion: false,
    requiresPointer: false,
  },
  {
    id: "paint-wars",
    title: "Paint Wars",
    description: "Point your phone to paint the floor. Claim the most territory to win.",
    minPlayers: 1,
    maxPlayers: 4,
    requiresMotion: true,
    requiresPointer: true,
  },
  {
    id: "trivia-buzzer",
    title: "Trivia Buzzer",
    description: "Tap the correct answer fastest to score.",
    minPlayers: 1,
    maxPlayers: 8,
    requiresMotion: false,
    requiresPointer: false,
  },
  {
    id: "sleeper-agent",
    title: "Sleeper Agent",
    description: "One of you is secretly the Agent. Talk it out, then vote them out.",
    minPlayers: 4,
    maxPlayers: 8,
    requiresMotion: false,
    requiresPointer: false,
  },
  {
    id: "doodle-relay",
    title: "Doodle Relay",
    description: "Draw the word on your phone. First to guess right scores.",
    minPlayers: 3,
    maxPlayers: 8,
    requiresMotion: false,
    requiresPointer: false,
  },
  {
    id: "draw-off",
    title: "Draw-Off",
    description: "Everyone draws the same word at once. An AI judges every drawing.",
    minPlayers: 2,
    maxPlayers: 8,
    requiresMotion: false,
    requiresPointer: false,
  },
  {
    id: "scream-royale",
    title: "Scream Royale",
    description: "Three rounds. Whoever's loudest wins.",
    minPlayers: 2,
    maxPlayers: 8,
    requiresMotion: false,
    requiresPointer: false,
    requiresMicrophone: true,
  },
  {
    id: "snap-judgment",
    title: "Snap Judgment",
    description: "Strike the pose. Everyone votes for the best one.",
    minPlayers: 2,
    maxPlayers: 8,
    requiresMotion: false,
    requiresPointer: false,
    requiresCamera: true,
  },
  {
    id: "echo-chain",
    title: "Echo Chain",
    description: "Say a word into your phone before time runs out. Repeat or freeze and you're out.",
    minPlayers: 2,
    maxPlayers: 8,
    requiresMotion: false,
    requiresPointer: false,
    requiresMicrophone: true,
  },
  {
    id: "plot-twist",
    title: "Plot Twist",
    description: "An AI dreams up an absurd scenario. Type the funniest response and vote for your favorite.",
    minPlayers: 3,
    maxPlayers: 8,
    requiresMotion: false,
    requiresPointer: false,
  },
  {
    id: "push-battle",
    title: "Push Battle",
    description: "Single-elimination tug-of-war. Mash your button to push the meter to your side.",
    minPlayers: 2,
    maxPlayers: 8,
    requiresMotion: false,
    requiresPointer: false,
  },
  {
    id: "ai-wildcard",
    title: "AI Wildcard",
    description: "An AI invents a brand-new mini-game on the spot. Nobody knows the rules until you do.",
    minPlayers: 2,
    maxPlayers: 8,
    requiresMotion: false,
    requiresPointer: false,
  },
  {
    id: "hot-potato",
    title: "Hot Potato",
    description: "Shake your phone hard to pass the potato before the hidden fuse runs out.",
    minPlayers: 2,
    maxPlayers: 8,
    requiresMotion: true,
    requiresPointer: false,
  },
];

export function getGameMeta(id: string): GameMeta | undefined {
  return GAME_REGISTRY.find((g) => g.id === id);
}
